name: release-tag

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      -
        name: Install Python packages
        run: pip install -r requirements.txt pyinstaller pyinstaller-versionfile
      -
        name: Create Pyinstaller version file
        run: create-version-file metadata.yml --outfile file_version_info.txt --version "${{ github.ref_name }}".Replace("v", "")
      -
        name: Build executable
        run: pyinstaller --noconfirm --clean --onefile --console --name exploit-host --version-file file_version_info.txt --distpath .\ --icon icon.ico start.py
      -
        name: Make release zips
        run: |
          Compress-Archive -Path ".\debug\", ".\exploits", ".\payloads", ".\pkgs", ".\themes", ".\updates", ".\exploit-host.exe", ".\LICENSE", ".\news.json", ".\README.md", ".\settings.json", ".\snakeoil.key", ".\snakeoil.pem" -CompressionLevel Optimal -DestinationPath .\exe-${{ github.ref_name }}.zip
          Compress-Archive -Path ".\debug\", ".\exploits", ".\fdns", ".\payloads", ".\pkgs", ".\themes", ".\updates", ".\start.py", ".\LICENSE", ".\news.json", ".\README.md", ".\requirements.txt", ".\settings.json", ".\snakeoil.key", ".\snakeoil.pem" -CompressionLevel Optimal -DestinationPath .\py-${{ github.ref_name }}.zip
      -
        name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          artifacts: |
            exe-${{ github.ref_name }}.zip
            py-${{ github.ref_name }}.zip
          draft: true
